### ISSUE TITLE
Improper HMI representation when using Firefox on Debian 10

### ISSUE THREAD

**Issue by spark706** [openenergysolutions/openfmb.hmi#8]
The  HMI using the localhost as viewed on Firefox is not appearing as nicely as when seen on Windows.  I have attached two images where you see the Actions are in text form without the icons found on Windows.  The links associated with the Actions are functional, just difficult to deal with if you are not familiar with what they are doing.

![20210618_091948](https://user-images.githubusercontent.com/27433514/122568122-6eff9180-d017-11eb-8e6c-b589809fd3cf.jpg)
![20210618_092009](https://user-images.githubusercontent.com/27433514/122568128-7030be80-d017-11eb-906f-1d45dae0fa52.jpg)

Unfortunately, the Linux machine is an off-network device and therefore limited to Firefox so I do not know if the issue is found in another browser on the same machine.

**Comment by corynguyenfl** [comment]
Fixed - Self host Google fonts for off-network machine.
https://github.com/openenergysolutions/openfmb.hmi/commit/c21ef5edfeae23b3b2e0b6be93ee674924f9ed29
